#!/bin/bash -ex

rm -f ~/.gitconfig

git config --global user.email "dbesen@gmail.com"
git config --global user.name "David Besen"
git config --global color.ui "true"
git config --global difftool.sdiff.cmd "sdiff -l -d "$LOCAL" "$REMOTE""
git config --global difftool.prompt "false"
git config --global alias.vimdiff "difftool -t vimdiff"
git config --global alias.sdiff "difftool -t sdiff"
git config --global branch.autosetuprebase "always"
git config --global log.date "local"
git config --global core.sparsecheckout "true"
git config --global core.repositoryformatversion "0"
git config --global core.filemode "true"
git config --global core.bare "false"
git config --global core.logallrefupdates "true"
git config --global rerere.enabled true
git config --global merge.conflictstyle diff3
git config --global alias.really-clean 'clean -X -d -f -f'
git config --global alias.would-clean 'clean -X -d -n'
git config --global git-up.fetch.all true
git config --global git-up.bundler.check false
git config --global push.default simple
git config --global http.sslVerify false
git config --global status.showuntrackedfiles all
git config --global alias.up 'pull --rebase --autostash'
git config --global pretty.oneline-s "%C(yellow)%h%Creset %<(20,trunc)%an %C(blue)%cs%Creset %s"
git config --global alias.branch-owners = "!f() { git for-each-ref refs/remotes/ --format='%(refname) %09 %(authorname) %09 %(committerdate)'; }; f | column -t -s'\t'"
