#!/bin/bash -ex

cd "$( dirname "${BASH_SOURCE[0]}" )"

./git-config
git config --global user.email "david.besen@hp.com"
git config --global http.proxy "web-proxy.austin.hp.com:8080"
git config --global gitreview.username "besen"
